### ISSUE TITLE
Yelp API verification

### ISSUE THREAD

**Issue by jamestw13** [jamestw13/Taco-Loca-tor#5]
Make sure Yelp API will return what we need
Make sure it's free to use and get an API key.

Suggested api endpoint: https://www.yelp.com/developers/documentation/v3/business_search
A different one may be more appropriate.

**Comment by jamestw13** [comment]
Found working API for restaurant searches:
https://rapidapi.com/restaurantmenus/api/documenu/

**Comment by vic-smith** [comment]
Decided to go with documenu.
